
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LocalServer1!
    restart: unless-stopped
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
